# -*- coding: utf-8 -*-
"""Chatbot_baseado_em_Conteudo_de_PDFs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VlGrzsbzWivu0VaH-zfQRJzyQde__dyy
"""

# Estrutura de arquivos
# /inputs/texto.txt
# /app.py
# /README.md

# Conteudo do app.py:

import streamlit as st
from langchain.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from langchain.llms import HuggingFaceHub
from langchain.chains import RetrievalQA

# Carregando documento
document_path = 'inputs/texto.txt'
loader = TextLoader(document_path)

# Dividindo texto
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
texts = text_splitter.split_documents(loader.load())

# Gerando embeddings
embeddings = HuggingFaceEmbeddings()
vectorstore = FAISS.from_documents(texts, embeddings)

# Carregando modelo
llm = HuggingFaceHub(repo_id="google/flan-t5-base", model_kwargs={"temperature":0, "max_length":512})
qa_chain = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=vectorstore.as_retriever())

# Streamlit Interface
st.title("Chatbot Inteligente baseado em PDFs")

user_question = st.text_input("Faça sua pergunta sobre o conteúdo:")

if user_question:
    response = qa_chain.run(user_question)
    st.write(response)

# Conteudo do README.md:

# Chatbot baseado em Conteúdo de PDFs

O projeto consiste em um chatbot que responde perguntas com base em documentos.

## Tecnologias utilizadas
- Python
- LangChain
- HuggingFace
- FAISS
- Streamlit

## Como utilizar
1. Suba seus textos no diretório `/inputs`
2. Execute o `app.py`
3. Interaja com o chatbot no navegador!

## Desenvolvido por:
**Rafael Queiroz**

---

# Conteudo do inputs/texto.txt